# Site settings
title: umami savvy
header-img: img/header.png
email: 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://umamisavvy.com"
twitter_username: 
github_username: 
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
