# Site settings
title: umami savvy
header-img: img/miyajima.jpg
email:
description: "Our first time in Japan."
baseurl: ""
url: "http://umamisavvy.com"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
